				INCLUDE <E:\Usuarios\Videos\Radeon ReLive\micro\EJERCICIOS\ENCABEZADO.asm>
				CLRF	TRISC				;SALIDA PC
				BCF		TRISB,7				;SALIDA C7
				BCF		STATUS,RP0			;B0
				CLRF	PORTC				;LIMPIAR PC
				BCF		PORTB,7				;LIMPIAR B7
CICLO			BTFSS	PORTB,0				;B0=1?
				GOTO	CICLO				
				MOVF	PORTD,W				
				MOVWF	PORTC				;C=D(DATO 1)
				MOVWF	0X20				;D(DATO 1) SE GUARDA EN 0X20
				BCF		PORTB,7				;LIMPIAR B7

REPETIRB1		BTFSS	PORTB,1				;B1=1?
				GOTO	REPETIRB2			
				GOTO	SUMA
REPETIRB2		BTFSS	PORTB,2				;B2=1?
				GOTO	REPETIRB3
				GOTO	RESTA
REPETIRB3		BTFSS	PORTB,3				;B3=1?
				GOTO	REPETIRB4
				GOTO	MULTIPLICACION
REPETIRB4		BTFSS	PORTB,4				;B4=1?
				GOTO	REPETIRB1
				GOTO	DIVISION

SUMA			MOVF	PORTD,W				;LEE PD Y GUARDA EN W
				MOVWF	0X25				;D(DATO 2) LO GUARDA EN 0X25
				ADDWF	0X20,W				;SUMA D(DATO 1)-D(DATO 2)
				MOVWF	PORTC				;LO MUESTRA EN PC
				BTFSS	STATUS,C			;C=1?
				GOTO	FINAL				
				BSF		PORTB,7				;B7 ENCIENDE
				GOTO	FINAL

RESTA			MOVF	PORTD,W				;LEE PD Y GUARDA EN W
				MOVWF	0X26				;D(DATO 2) LO GUARDA EN 0X26
				SUBWF	0X20,W				;RESTA D(DATO 1)-D(DATO 2)
				BTFSS	STATUS,C			;C=1?
				GOTO	MAGNITUD		
				MOVWF	PORTC				;MUESTRA PC
				GOTO	FINAL
MAGNITUD		SUBLW	0X00				;PC=|PD(DATO 1)-PD(DATO 2)|
				MOVWF	PORTC				;MUESTRA PC
				BSF		PORTB,7
				GOTO	FINAL		
				

MULTIPLICACION	GOTO FINAL

DIVISION		GOTO FINAL


FINAL			GOTO	CICLO
				END
