; INSTITUTO POLITECNICO NACIONAL
; UPIITA
; uP, uC e I
; 17 NOV 2020
; CRD, FOLM, VVAD
; PRACTICA 1: USO DE PUERTOS Y OPERACIONES
; DAVID ARTURO GUTIERREZ BEGOVICH
; ESCRITO PARA PIC16F887 EN ENSAMBLADOR (MPLAB 8.91)		

				CLRF	TRISC				;SALIDA PC
				BCF		TRISB,7				;SALIDA B7
				BCF		STATUS,RP0			;B0
				CLRF	PORTC				;LIMPIAR PC
				BCF		PORTB,7				;LIMPIAR B7
CICLO			BTFSS	PORTB,0				;B0=1?
				GOTO	CICLO				
				MOVF	PORTD,W				
				MOVWF	PORTC				;C=D(DATO 1)
				MOVWF	0X20				;D(DATO 1) SE GUARDA EN 0X20
				BCF		PORTB,7				;LIMPIAR B7


REPETIRB1		BTFSS	PORTB,1				;B1=1?
				GOTO	REPETIRB2			
				GOTO	SUMA
REPETIRB2		BTFSS	PORTB,2				;B2=1?
				GOTO	REPETIRB3
				GOTO	RESTA
REPETIRB3		BTFSS	PORTB,3				;B3=1?
				GOTO	REPETIRB4
				GOTO	MULTIPLICACION
REPETIRB4		BTFSS	PORTB,4				;B1=1?
				GOTO	REPETIRB1
				GOTO	DIVISION

;--------------------------SUMA---------------------------------------------
SUMA			MOVF	PORTD,W				;LEE PD Y GUARDA EN W
				MOVWF	0X25				;D(DATO 2) LO GUARDA EN 0X25
				ADDWF	0X20,W				;SUMA D(DATO 1)+D(DATO 2)
				BTFSS	STATUS,C			;C=1?
				GOTO	FINAL				
				BSF		PORTB,7				;B7 ENCIENDE
				GOTO	FINAL
;--------------------------RESTA--------------------------------------------
RESTA			MOVF	PORTD,W				;LEE PD Y GUARDA EN W
				MOVWF	0X26				;D(DATO 2) LO GUARDA EN 0X26
				SUBWF	0X20,W				;RESTA D(DATO 1)-D(DATO 2)
				BTFSS	STATUS,C			;C=1?
				GOTO	MAGNITUD		
				MOVWF	PORTC				;MUESTRA PC
				GOTO	FINAL
MAGNITUD		SUBLW	0X00				;PC=|PD(DATO 1)-PD(DATO 2)|
				MOVWF	PORTC				;MUESTRA PC
				BSF		PORTB,7
				GOTO	FINAL		

;----------------------------MULTIPLICACION-----------------------------------
MULTI_O			EQU		0X21		   		;DATO A SUMAR (MULTIPLICANDO).
MULTI_R   		EQU		0X22		    	;VECES A SUMAR(MULTIPLICADOR).
SUMAT			EQU		0X23		    	;SUMA DE LOS DATOS
;------------------------------------------------------------------------

MULTIPLICACION	MOVF	PORTD,W
				MOVWF	0X27				;D(DATO 2) LO GUARDA EN 0X27
				MOVWF	MULTI_R				;MULIT_R A W
				MOVF	0X20,W		    	;MOVEMOS MULTI_R A 0X20.
				MOVWF	MULTI_O			    ;MUEVE W A REG MULTI_O
				CLRF	W					;LIMPIAMOS ACUMULADOR
				MOVF	MULTI_O,F			;F=MULTI_O
				BTFSS	STATUS,Z	    	;Z=0?.
CONDICION2:		GOTO	CONDICION1	
				GOTO	FINAL

CONDICION1:		MOVF	MULTI_R,F
				BTFSS	STATUS,Z	    	;MULTI_R = 0?.
				GOTO	MULTI_R
				GOTO	CONDICION3

MULTIPLICAR		MOVF	MULTI_O,W   		;MUEVE MULTI_O A WREG.
				ADDWF	SUMAT,F		    	;SUMAT = SUMAT + MULTI_O.
				BTFSC	STATUS,C	    	;HAY ACARREO?, C=O?.
				BSF		PORTB,7
				DECF	MULTI_R,F	    	;DECREMENTA EN 1 Y GUARDA EN EL MISMO.
				GOTO	CONDICION2
CONDICION3:		MOVF	SUMAT,W		    	;MUEVE ST A WREG.
				GOTO	FINAL
				

;----------------------------DIVISION----------------------------------------
NUMERADOR	        EQU     0X31                
DENOMINADOR  		EQU		0X32		    	
COCIENTE			EQU		0X33		    	
RESIDUO				EQU     0X34				
DIVISION			GOTO 	FINAL
;----------------------------------------------------------------------------------

DIVISION		MOVF	PORTD,W
				MOVWF	0X30				;D(DATO 2) LO GUARDA EN 0X30
				MOVWF	NUMERADOR			;NUMERADOR A W
				MOVF	0X32,W		    	;MOVEMOS NUMERADOR A 0X32
				MOVWF	DENOMINADOR			;MUEVE W A DENOMINADOR
				CLRF	W					;LIMPIAMOS ACUMULADOR
				MOVF	NUMERADOR,F			;F=NUMERADOR
				BTFSS	STATUS,Z	    	;¿DENOMINADOR=0?
				GOTO 	DIVIDIR
				GOTO 	DIV-ACA
				GOTO	FINAL
				GOTO	MIMIR

DIVIDIR			MOVF	NUMERADOR,0			;MUEVE NUMERADOR A W
				SUBWF   NUMERADOR,1			; NUMERADOR = NUMERADOR - DENOMINADOR
				INCF	COCIENTE,1			; AGREGA UN 1 AL COCIENTE
				GOTO 	DIVISION
				 
DIV-ACA			MOVF	NUMERADOR,1			; GUARDA NUMERADOR EN W
				BTFSS	STATUS,Z			; ¿NUMERADOR =0?
				BSF		PORTB,7				; FLAG ACARREO
				MOVF	COCIENTE,0			; MOVER COCIENTE A W
				GOTO 	ENDPROG



FINAL			MOVWF	PORTC				;LO MUESTRA EN PC
				GOTO	CICLO
				
MIMIR			SLEEP



				END 